config/routes.rb
Rails.application.routes.draw do
  resources :lista do
    resources :lista_clientes
  end
  resources :campaigns
  root 'lista#index'
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/campaign.rb
class Campaign < ApplicationRecord

end

app/models/lista_cliente.rb
class ListaCliente < ApplicationRecord
    belongs_to :Campaign
end

app/models/listum.rb
class Listum < ApplicationRecord
    has_many :lista_cliente        
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/campaigns_controller.rb
class CampaignsController < ApplicationController
  before_action :set_campaign, only: [:show, :edit, :update, :destroy]

  # GET /campaigns
  # GET /campaigns.json
  def index
    @campaigns = Campaign.all
  end

  # GET /campaigns/1
  # GET /campaigns/1.json
  def show
  end

  # GET /campaigns/new
  def new
    @campaign = Campaign.new
  end

  # GET /campaigns/1/edit
  def edit
  end

  # POST /campaigns
  # POST /campaigns.json
  def create
    @campaign = Campaign.new(campaign_params)

    respond_to do |format|
      if @campaign.save
        format.html { redirect_to @campaign, notice: 'Campaign was successfully created.' }
        format.json { render :show, status: :created, location: @campaign }
      else
        format.html { render :new }
        format.json { render json: @campaign.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /campaigns/1
  # PATCH/PUT /campaigns/1.json
  def update
    respond_to do |format|
      if @campaign.update(campaign_params)
        format.html { redirect_to @campaign, notice: 'Campaign was successfully updated.' }
        format.json { render :show, status: :ok, location: @campaign }
      else
        format.html { render :edit }
        format.json { render json: @campaign.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /campaigns/1
  # DELETE /campaigns/1.json
  def destroy
    @campaign.destroy
    respond_to do |format|
      format.html { redirect_to campaigns_url, notice: 'Campaign was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_campaign
      @campaign = Campaign.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def campaign_params
      params.require(:campaign).permit(:nombre, :fecha_inicio, :fecha_fin, :segmento_cliente, :lista_distribucion_clientes, :lista_productos)
    end
end

app/controllers/lista_clientes_controller.rb
class ListaClientesController < ApplicationController
  before_action :set_lista_cliente, only: [:show, :edit, :update, :destroy]

  # GET /lista_clientes
  # GET /lista_clientes.json
  def index
    @lista_clientes = ListaCliente.all
  end

  # GET /lista_clientes/1
  # GET /lista_clientes/1.json
  def show
  end

  # GET /lista_clientes/new
  def new
    @listum = Listum.find(params[:listum_id])
    @lista_cliente = @listum.lista_cliente.new
  end

  # GET /lista_clientes/1/edit
  def edit
  end

  # POST /lista_clientes
  # POST /lista_clientes.json
  def create
    @listum = Listum.find(params[:listum_id])
    @lista_cliente = @listum.lista_cliente.new(lista_cliente_params)

    respond_to do |format|
      if @lista_cliente.save
        format.html { redirect_to @lista_cliente, notice: 'Lista cliente was successfully created.' }
        format.json { render :show, status: :created, location: @lista_cliente }
      else
        format.html { render :new }
        format.json { render json: @lista_cliente.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lista_clientes/1
  # PATCH/PUT /lista_clientes/1.json
  def update
    respond_to do |format|
      if @lista_cliente.update(lista_cliente_params)
        format.html { redirect_to @lista_cliente, notice: 'Lista cliente was successfully updated.' }
        format.json { render :show, status: :ok, location: @lista_cliente }
      else
        format.html { render :edit }
        format.json { render json: @lista_cliente.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lista_clientes/1
  # DELETE /lista_clientes/1.json
  def destroy
    @lista_cliente.destroy
    respond_to do |format|
      format.html { redirect_to lista_clientes_url, notice: 'Lista cliente was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_lista_cliente
      @lista_cliente = ListaCliente.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def lista_cliente_params
      params.require(:lista_cliente).permit(:cliente, :correo)
    end
end

app/controllers/lista_controller.rb
class ListaController < ApplicationController
  before_action :set_listum, only: [:show, :edit, :update, :destroy]

  # GET /lista
  # GET /lista.json
  def index
    @lista = Listum.all
  end

  # GET /lista/1
  # GET /lista/1.json
  def show
  end

  # GET /lista/new
  def new
    @listum = Listum.new
  end

  # GET /lista/1/edit
  def edit
  end

  # POST /lista
  # POST /lista.json
  def create
    @listum = Listum.new(listum_params)

    respond_to do |format|
      if @listum.save
        format.html { redirect_to @listum, notice: 'Listum was successfully created.' }
        format.json { render :show, status: :created, location: @listum }
      else
        format.html { render :new }
        format.json { render json: @listum.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lista/1
  # PATCH/PUT /lista/1.json
  def update
    respond_to do |format|
      if @listum.update(listum_params)
        format.html { redirect_to @listum, notice: 'Listum was successfully updated.' }
        format.json { render :show, status: :ok, location: @listum }
      else
        format.html { render :edit }
        format.json { render json: @listum.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lista/1
  # DELETE /lista/1.json
  def destroy
    @listum.destroy
    respond_to do |format|
      format.html { redirect_to lista_url, notice: 'Listum was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_listum
      @listum = Listum.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def listum_params
      params.require(:listum).permit(:nombre)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/campaigns_helper.rb
module CampaignsHelper
end

app/helpers/lista_clientes_helper.rb
module ListaClientesHelper
end

app/helpers/lista_helper.rb
module ListaHelper
end

app/views/campaigns/_form.html.erb
<%= form_with(model: campaign, local: true) do |form| %>
  <% if campaign.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(campaign.errors.count, "error") %> prohibited this campaign from being saved:</h2>

      <ul>
      <% campaign.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nombre %>
    <%= form.text_area :nombre, id: :campaign_nombre %>
  </div>

  <div class="field">
    <%= form.label :fecha_inicio %>
    <%= form.date_select :fecha_inicio, id: :campaign_fecha_inicio %>
  </div>

  <div class="field">
    <%= form.label :fecha_fin %>
    <%= form.date_select :fecha_fin, id: :campaign_fecha_fin %>
  </div>

  <div class="field">
    <%= form.label :segmento_cliente %>
    <%= form.text_area :segmento_cliente, id: :campaign_segmento_cliente %>
  </div>

  <div class="field">
    <%= form.label :lista_distribucion_clientes %>
    <%= form.number_field :lista_distribucion_clientes, id: :campaign_lista_distribucion_clientes %>
  </div>

  <div class="field">
    <%= form.label :lista_productos %>
    <%= form.number_field :lista_productos, id: :campaign_lista_productos %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/campaigns/edit.html.erb
<h1>Editing Campaign</h1>

<%= render 'form', campaign: @campaign %>

<%= link_to 'Show', @campaign %> |
<%= link_to 'Back', campaigns_path %>

app/views/campaigns/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Campaigns</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Fecha inicio</th>
      <th>Fecha fin</th>
      <th>Segmento cliente</th>
      <th>Lista distribucion clientes</th>
      <th>Lista productos</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @campaigns.each do |campaign| %>
      <tr>
        <td><%= campaign.nombre %></td>
        <td><%= campaign.fecha_inicio %></td>
        <td><%= campaign.fecha_fin %></td>
        <td><%= campaign.segmento_cliente %></td>
        <td><%= campaign.lista_distribucion_clientes %></td>
        <td><%= campaign.lista_productos %></td>
        <td><%= link_to 'Show', campaign %></td>
        <td><%= link_to 'Edit', edit_campaign_path(campaign) %></td>
        <td><%= link_to 'Destroy', campaign, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Campaign', new_campaign_path %>

app/views/campaigns/new.html.erb
<h1>New Campaign</h1>

<%= render 'form', campaign: @campaign %>

<%= link_to 'Back', campaigns_path %>

app/views/campaigns/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @campaign.nombre %>
</p>

<p>
  <strong>Fecha inicio:</strong>
  <%= @campaign.fecha_inicio %>
</p>

<p>
  <strong>Fecha fin:</strong>
  <%= @campaign.fecha_fin %>
</p>

<p>
  <strong>Segmento cliente:</strong>
  <%= @campaign.segmento_cliente %>
</p>

<p>
  <strong>Lista distribucion clientes:</strong>
  <%= @campaign.lista_distribucion_clientes %>
</p>

<p>
  <strong>Lista productos:</strong>
  <%= @campaign.lista_productos %>
</p>

<%= link_to 'Edit', edit_campaign_path(@campaign) %> |
<%= link_to 'Back', campaigns_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AppCampaign</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lista/_form.html.erb
<%= form_with(model: listum, local: true) do |form| %>
  <% if listum.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(listum.errors.count, "error") %> prohibited this listum from being saved:</h2>

      <ul>
      <% listum.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nombre %>
    <%= form.text_area :nombre, id: :listum_nombre %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/lista/edit.html.erb
<h1>Editing Listum</h1>

<%= render 'form', listum: @listum %>

<%= link_to 'Show', @listum %> |
<%= link_to 'Back', lista_path %>

app/views/lista/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Lista</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @lista.each do |listum| %>
      <tr>
        <td><%= listum.nombre %></td>
        <td><%= link_to 'Show', listum %></td>
        <td><%= link_to 'Edit', edit_listum_path(listum) %></td>
        <td><%= link_to 'Destroy', listum, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Listum', new_listum_path %>

app/views/lista/new.html.erb
<h1>New Listum</h1>

<%= render 'form', listum: @listum %>

<%= link_to 'Back', lista_path %>

app/views/lista/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @listum.nombre %>
</p>

<%= link_to 'Edit', edit_listum_path(@listum) %> |
<%= link_to 'Back', lista_path %>

app/views/lista_clientes/_form.html.erb
<%= form_with(model: lista_cliente, local: true) do |form| %>
  <% if lista_cliente.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(lista_cliente.errors.count, "error") %> prohibited this lista_cliente from being saved:</h2>

      <ul>
      <% lista_cliente.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :cliente %>
    <%= form.number_field :cliente, id: :lista_cliente_cliente %>
  </div>

  <div class="field">
    <%= form.label :correo %>
    <%= form.text_area :correo, id: :lista_cliente_correo %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/lista_clientes/edit.html.erb
<h1>Editing Lista Cliente</h1>

<%= render 'form', lista_cliente: @lista_cliente %>

<%= link_to 'Show', @lista_cliente %> |
<%= link_to 'Back', lista_clientes_path %>

app/views/lista_clientes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Lista Clientes</h1>

<table>
  <thead>
    <tr>
      <th>Cliente</th>
      <th>Correo</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @lista_clientes.each do |lista_cliente| %>
      <tr>
        <td><%= lista_cliente.cliente %></td>
        <td><%= lista_cliente.correo %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/lista_clientes/new.html.erb
<h1>New Lista Cliente</h1>

<%= render 'form', lista_cliente: @lista_cliente %>

<%= link_to 'Back', lista_clientes_path %>

app/views/lista_clientes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Cliente:</strong>
  <%= @lista_cliente.cliente %>
</p>

<p>
  <strong>Correo:</strong>
  <%= @lista_cliente.correo %>
</p>

<%= link_to 'Edit', edit_lista_cliente_path(@lista_cliente) %> |
<%= link_to 'Back', lista_clientes_path %>